title: Total Information Management Ltd.
description: ICT Policy, Strategy & Development Consultants - Nairobi, Kenya

url: "https://totalinfomationmanagement.github.io"
baseurl: "/tim-website-jeykll"

theme: null

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /news/:slug/
future: true

# Tell Jekyll to look for posts in ALL subdirectories of _posts
collections_dir: .

# Explicitly define posts collection
collections:
  posts:
    output: true
    permalink: /news/:slug/

# Defaults for all posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      author: TiM Editorial Team
      published: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
