title: Total Information Management Ltd.
description: ICT Policy, Strategy & Development Consultants — Nairobi, Kenya
url: ""
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /news/:slug/

# Collections
collections:
  posts:
    output: true
    permalink: /news/:slug/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      author: TiM Editorial Team

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
